language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
dist: trusty
env:
  - YTDL_TEST_SET=core
jobs:
  include:
    - python: 3.7
      dist: xenial
      env: YTDL_TEST_SET=core
    - python: 3.8
      dist: xenial
      env: YTDL_TEST_SET=core
    - python: 3.8-dev
      dist: xenial
      env: YTDL_TEST_SET=core
    - env: JYTHON=true; YTDL_TEST_SET=core
    - name: flake8
      python: 3.8
      dist: xenial
      install: pip install flake8
      script: flake8 .
  fast_finish: true
  allow_failures:
    - env: YTDL_TEST_SET=download
    - env: JYTHON=true; YTDL_TEST_SET=core
before_install:
  - if [ "$JYTHON" == "true" ]; then ./devscripts/install_jython.sh; export PATH="$HOME/jython/bin:$PATH"; fi
script: ./devscripts/run_tests.sh
